name: 定时获取投票数据

on:
  schedule:
    # 每天 12:05 (GMT+8) 运行，即 UTC 04:05
    - cron: '5 4 * * *'
  workflow_dispatch:
    inputs:
      stage:
        description: '投票阶段 (first/second)'
        required: true
        default: 'first'
        type: choice
        options:
          - first
          - second

jobs:
  fetch-votes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 执行数据获取脚本
        env:
          VOTING_STAGE: ${{ github.event.inputs.stage || 'first' }}
        run: node scripts/fetchVotes.js

      - name: 检查数据变化
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交数据更新
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*.json.gz
          git commit -m "data: snapshot $(date '+%F %T')"
          git push

      - name: 部署到 GitHub Pages
        if: steps.check-changes.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          enable_jekyll: false
        env:
          NODE_ENV: production 